The goal here is to find the magnitude cuts for different years when fixing Y1 limiting i-band magnitude to be 24.5 and that for Y10 to be 26.0.

Basically we have to consider log(t) scaling in between the two limiting magnitudes. Log(t) since flux scales as $\sqrt{t}$ and since magnitude $\propto$ 2.5log(flux), we have magnitude $\propto$ 2.5log($\sqrt{t}$) = 1.25log(t)

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from scipy.interpolate import interp1d

In [2]:
cuts = [24.5, 26.0]
yrs = [1, 10.]

f = interp1d(x=np.log(yrs), y=cuts)

In [3]:
y2 = np.arange(yrs[0], yrs[1]+1)
for y, m in zip(y2,f(np.log(y2))):
    print('Y%s: i_lim = %.2f'%(y, m))

Y1.0: i_lim = 24.50
Y2.0: i_lim = 24.95
Y3.0: i_lim = 25.22
Y4.0: i_lim = 25.40
Y5.0: i_lim = 25.55
Y6.0: i_lim = 25.67
Y7.0: i_lim = 25.77
Y8.0: i_lim = 25.85
Y9.0: i_lim = 25.93
Y10.0: i_lim = 26.00


Comparing these to the cuts currently implemented( Y1, Y3, Y6, Y10: 24.5, 25.0, 25.5, 26), we basically have more loose cuts for Y3 and Y6 than one would have based on log(t) interpolation. Since we want cuts for all intermediates years, lets just fix the four depths cuts and interpolate in between.

In [4]:
cuts = [24.5, 25.0]
yrs = [1, 3]

f = interp1d(x=np.log(yrs), y=cuts)

y2 = np.arange(yrs[0], yrs[1]+1)
for y, m in zip(y2,f(np.log(y2))):
    print('Y%s: i_lim = %.2f'%(y, m))

Y1: i_lim = 24.50
Y2: i_lim = 24.82
Y3: i_lim = 25.00


In [5]:
cuts = [25.0, 25.5]
yrs = [3, 6]

f = interp1d(x=np.log(yrs), y=cuts)

y2 = np.arange(yrs[0], yrs[1]+1)
for y, m in zip(y2,f(np.log(y2))):
    print('Y%s: i_lim = %.2f'%(y, m))

Y3: i_lim = 25.00
Y4: i_lim = 25.21
Y5: i_lim = 25.37
Y6: i_lim = 25.50


In [6]:
cuts = [25.5, 26.0]
yrs = [6, 10]

f = interp1d(x=np.log(yrs), y=cuts)

y2 = np.arange(yrs[0], yrs[1]+1)
for y, m in zip(y2,f(np.log(y2))):
    print('Y%s: i_lim = %.2f'%(y, m))

Y6: i_lim = 25.50
Y7: i_lim = 25.65
Y8: i_lim = 25.78
Y9: i_lim = 25.90
Y10: i_lim = 26.00


So we have: limiting mags for (Y1, Y2, Y3, Y4, Y5, Y6, Y7, Y8, Y9, Y10) = (24.5, 24.82, 25.0, 25.21, 25.37, 25.50, 25.65, 25.78, 25.90, 26.0).